export type JsonRecord = Record<string, unknown>;
export type ProfileRecord = {
  firstName: string;
  lastName: string;
  employeeNumber: string;
  workEmail: string;
  status: string;
  startDate: string;
  phone?: string;
  personalEmail?: string;
  address?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  country?: string;
  dateOfBirth?: string;
  gender?: string;
  maritalStatus?: string;
  nationality?: string;
  bloodGroup?: string;
  taxIdentifier?: string;
  bankName?: string;
  bankAccountNumber?: string;
  department?: { name: string };
  jobTitle?: { name: string };
  manager?: { firstName: string; lastName: string };
  documents: Array<{ id: string; name: string; type: string; url: string }>;
  profileChangeRequests: Array<{ id: string; section: string; status: string; createdAt: string }>;
  essProfile?: {
    employment: JsonRecord;
    personal: JsonRecord;
    family: JsonRecord[];
    nominees: JsonRecord[];
    immigration: JsonRecord[];
    licenses: JsonRecord[];
    skills: JsonRecord[];
    languages: JsonRecord[];
    qualifications: JsonRecord[];
    assets: JsonRecord[];
    experience: JsonRecord[];
    social: JsonRecord[];
  };
};
export type ProfileTab = "employment" | "personal" | "family" | "documents" | "skills" | "assets";
export type ProfileEditTab = "contact" | "personal" | "family" | "career";
