import express from "express";
import cors from "cors";
import helmet from "helmet";
import compression from "compression";
import rateLimit from "express-rate-limit";
import morgan from "morgan";
import swaggerUi from "swagger-ui-express";
import { config } from "./config.js";
import { errorHandler } from "./lib/errors.js";
import { authRouter } from "./modules/auth/auth.routes.js";
import { employeeRouter } from "./modules/employees/employee.routes.js";
import { leaveRouter } from "./modules/leave/leave.routes.js";
import { dashboardRouter } from "./modules/dashboard/dashboard.routes.js";
import { coreRouter } from "./modules/core/core.routes.js";
import { openApiDocument } from "./openapi.js";
import { organizationRouter } from "./modules/organization/organization.routes.js";
import { projectRouter } from "./modules/projects/project.routes.js";
import { notificationRouter } from "./modules/notifications/notification.routes.js";
import { essRouter } from "./modules/ess/ess.routes.js";

export const app = express();
app.set("trust proxy", 1);
app.use(helmet());
app.use(cors({ origin: config.WEB_URL, credentials: true }));
app.use(compression());
app.use(express.json({ limit: "1mb" }));
app.use(morgan(config.NODE_ENV === "production" ? "combined" : "dev"));
app.use("/api/v1/auth", rateLimit({ windowMs: 15 * 60 * 1000, limit: 100 }), authRouter);
app.use("/api/v1/employees", employeeRouter);
app.use("/api/v1/leave", leaveRouter);
app.use("/api/v1/dashboard", dashboardRouter);
app.use("/api/v1", coreRouter);
app.use("/api/v1", organizationRouter);
app.use("/api/v1", projectRouter);
app.use("/api/v1", notificationRouter);
app.use("/api/v1", essRouter);
app.get("/health", (_req, res) => res.json({ status: "ok", service: "nutrivae-api-gateway" }));
app.use("/docs", swaggerUi.serve, swaggerUi.setup(openApiDocument));
app.use((_req, res) => res.status(404).json({ error: { code: "NOT_FOUND", message: "Route not found." } }));
app.use(errorHandler);
